name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Test Case: Test One"
        id: test-one
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: test-one
          command: "echo \"Hello World\""
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grade Report
        uses: ./ # Uses an action in the root directory
        env:
          ATLAS_TOTAL_POINTS: 50
          ATLAS_TEST_TEST-ONE: "${{steps.test-one.outputs.result}}"